INSERT INTO Blog (title, content, published, externalLink) VALUES
('Spring Boot + Micrometer: Metrics to Send to CloudWatch Metrics and Configuration Method', '', 1, 'https://dev.classmethod.jp/en/articles/20260327-micrometer-cwl/'),
('How to Remap CapsLock to Conversion Key on Cosmic Desktop', '', 1, 'https://zenn.dev/seiichi1101/articles/cosmicos-capslock?locale=en'),
('A Deep Dive into the Implementation of Kotlin HashMap', '', 1, 'https://zenn.dev/seiichi1101/articles/kotlin-hashmap?locale=en'),
('Implementing a Custom Stream to Understand Java''s Stream API', '', 1, 'https://zenn.dev/seiichi1101/articles/java-my-stream?locale=en'),
('Implementing ReBAC (Relationship-Based Access Control) with Permit.io', '', 1, 'https://zenn.dev/seiichi1101/articles/permitio-rebac?locale=en'),
('Implementing ABAC (Attribute-Based Access Control) with Permit.io', '', 1, 'https://zenn.dev/seiichi1101/articles/permitio-abac?locale=en'),
('Implementing Web API Access Control with Permit.io', '', 1, 'https://zenn.dev/seiichi1101/articles/permitio-tutorial?locale=en'),
('Recap of AWS Community Day DACH 2025: Rethinking CloudWatch: Advanced AWS-native Observability That Can Save You $100k+ On 3rd Party Tools', '', 1, 'https://dev.classmethod.jp/articles/recap-of-aws-community-day-dach-2025-rethinking-cloudwatch-advanced-aws/'),
('Recap of AWS Community Day DACH 2025: Implementing Compliance in AWS with Terraform', '', 1, 'https://dev.classmethod.jp/articles/recap-of-aws-community-day-dach-2025-implementing-compliance-in-aws-with/'),
('I participated in AWS Community Day DACH 2025, one of the largest AWS community events in Europe', '', 1, 'https://dev.classmethod.jp/en/articles/aws-community-day-dach-2025-report/'),
('Exploring the potential of Amazon Verified Permissions as a Web API access controller', '', 1, 'https://dev.classmethod.jp/en/articles/web-api-amazon-verified-permissions/'),
('Deploying gRPC Servers to ECS with AWS Copilot CLI', '', 1, 'https://zenn.dev/seiichi1101/articles/copilot-grpc-go?locale=en'),
('Building a React SPA with Google OAuth 2.0 to Call the Google Tasks API', '', 1, 'https://zenn.dev/seiichi1101/articles/google-oauth2-react-spa?locale=en'),
('OpenSearch configuration patterns', '', 1 ,'https://dev.classmethod.jp/en/articles/opensearch-design-pattern/'),
('ECS Execute コマンドを CloudWatch Logs に出力する', '', 1 ,'https://dev.classmethod.jp/articles/ecs-exec-cmd-logging-demo/'),
('ヨーロッパ最大級の AWS コミュニティイベントに潜入！欧州でのトレンドを偵察してきた', '', 1 ,'https://dev.classmethod.jp/articles/2023-09-14-dach-event-report/'),
('CloudflareのWeb3 IPFS Gatewayを使ってIFPS上のウェブページにDNSLink経由でアクセスする', '', 1 ,'https://dev.classmethod.jp/articles/cloudflare-web3-ipfs-gateway/'),
('ゲームチェンジャーと噂の CloudFlare D1 を性能検証してみた', '', 1 ,'https://dev.classmethod.jp/articles/cloudflare-d1-performance-survey/'),
('コンシューマー・エレクトロニクスの祭典「IFA Berlin 2022」に参加してきた', '', 1 ,'https://dev.classmethod.jp/articles/ifa-berlin-2022/'),
('エンジニアだけどドイツに移住してみた', '', 1 ,'https://dev.classmethod.jp/articles/immigrate-to-germany/'),
('Djangoで組織とユーザーの権限の管理をやってみる #devio2022', '', 1 ,'https://dev.classmethod.jp/articles/django-user-org-permission/'),
('NewRelicのダッシュボードのスナップショットを定期的にSlackへ送信する仕組みをAWSで作ってみた', '', 1 ,'https://dev.classmethod.jp/articles/newrelic-dashboard-slack-exporter/'),
('AWSではじめるブロックチェーン Amazon Managed Blockchain', '', 1 ,'https://dev.classmethod.jp/articles/amb-tutorial/'),
('2021年10-12月のMAD事業部メンバーのOSSコントリビューションについてご紹介します', '', 1 ,'https://dev.classmethod.jp/articles/2021-2q-mad-div-oss-contributes/'),
('双方向ストリーミングな gRPC サーバーを GKE にデプロイしてみる', '', 1 ,'https://dev.classmethod.jp/articles/google-kubernetes-engin-grpc-stream/'),
('[セッションレポート] グラフデータベース Amazon Neptune の事例紹介～LexisNexis社～ #reinvent #DAT202', '', 1 ,'https://dev.classmethod.jp/articles/real-world-use-cases-with-graph-databases/'),
('Google Cloud Runを使って双方向ストリーミングな gRPC サーバーを構築してみる', '', 1, 'https://dev.classmethod.jp/articles/google-cloud-run-grpc-stream/'),
('〖はじめてのGoogle Cloud〗Terraformと gcloud コマンドで Django App を GAE にデプロイしてみた', '', 1, 'https://dev.classmethod.jp/articles/django-gae-terraform/'),
('Goテストモジュール Testify をつかってみた', '', 1, 'https://dev.classmethod.jp/articles/go-testify/'),
('不適切なワードや画像を手軽に検出できる SaaS WebPurify をつかってみた', '', 1, 'https://dev.classmethod.jp/articles/profanity-filter-saas/'),
('Amazon Neptune のトランザクションについて完全に理解した', '', 1, 'https://dev.classmethod.jp/articles/amazon-neptune-transaction/'),
('Ubuntu on WSL ユーザーのためPC移行ガイド', '', 1, 'https://dev.classmethod.jp/articles/wsl-migration/'),
('Go言語のグラフデータモデル用 ORM ent が良かった', '', 1, 'https://dev.classmethod.jp/articles/go-gremlin-orm-ent/'),
('NewRelicでgRPC対応のGoエージェントが利用できるそうなので導入してみた', '', 1, 'https://dev.classmethod.jp/articles/newrelic-grpc-apm-golang/'),
('API Gateway Websocket を Golang でためしてみる', '', 1, 'https://dev.classmethod.jp/articles/apigw-websocket-golang/'),
('[アップデート] TerraformでgRPCのALBターゲットグループが作成できるようになりました！', '', 1, 'https://dev.classmethod.jp/articles/grpc-terraform/'),
('はじめての GraphDB Amazon Neptune', '', 1, 'https://dev.classmethod.jp/articles/first-time-graphdb-amazon-neptune/'),
('Auth0で保護されたGo gRPC サーバーを AWS 上に構築してみる', '', 1, 'https://dev.classmethod.jp/articles/go-grpc-auth0-aws/'),
('Auth0経由でGoogleログインしたユーザーで AWS AppSync へ接続するサンプルアプリをReact Nativeで作ってみた', '', 1, 'https://dev.classmethod.jp/articles/auth0-react-native-appsyc/'),
('カオスエンジニアリングツール Gremlin で ECS 上の PHP アプリケーションに CPU 負荷を注入してみた', '', 1, 'https://dev.classmethod.jp/articles/gremlin_ecs_php_sample_app/'),
('2020年09月25日 ウェビナー「はじめてのカオスエンジニアリング：Gremlin」のQAを公開します！', '', 1, 'https://dev.classmethod.jp/articles/gremlin_workshop_qa_20200925/'),
('「AWS Glueを使った Serverless ETL の実装パターン」について発表しました #devio2020', '', 1, 'https://dev.classmethod.jp/articles/developers-io-2020-connect-severless-etl-on-aws-glue/'),
('AWS Lake Formationのチュートリアルをやってみた！', '', 1, 'https://dev.classmethod.jp/articles/lakeformation_tutorial/'),
('Amazon Redshift Spectrumのチュートリアルをやってみた！', '', 1, 'https://dev.classmethod.jp/articles/redshift_spectrum_tutorial/'),
('Amazon Redshiftのチュートリアルをやってみた！', '', 1, 'https://dev.classmethod.jp/articles/redshift_tutorial/'),
('〖小ネタ〗消し忘れのリモートブランチを一括表示・削除するワンライナー', '', 1, 'https://dev.classmethod.jp/articles/git_remove_merged_branch/'),
('TerraformでLambda(Python)のデプロイを行うときのプラクティス', '', 1, 'https://dev.classmethod.jp/articles/terraform-lambda-deployment/'),
('Sphinxのイケてるドキュメントを自動デプロイして S3 で公開する！', '', 1, 'https://dev.classmethod.jp/articles/sphinx_auto_deployment_to_aws_s3/'),
('Pythonでインスタンス変数の入力値をバリデーションする方法', '', 1, 'https://dev.classmethod.jp/articles/python_class_instance_validation/'),
('BoxのWebhookを利用してAWS S3にファイルを同期する仕組みをサーバーレスで構築してみた！', '', 1, 'https://dev.classmethod.jp/articles/box_webhook_to_apigw/'),
('Glue Jobが失敗したらメール通知する超簡単な方法', '', 1, 'https://dev.classmethod.jp/articles/glue_job_err_notification/'),
('Pythonでログ出力をテストする LogCapture を使ってみた', '', 1, 'https://dev.classmethod.jp/articles/python_logcapture/'),
('〖アップデート〗ストリームベースで起動するLambdaのエラーハンドリングがやりやすくなったよ！', '', 1, 'https://dev.classmethod.jp/articles/stream-lambda-failure-handling/'),
('AWS Glueデータカタログのスキーマが後から変更された際の挙動について調べてみた', '', 1, 'https://dev.classmethod.jp/articles/glue_catalog_test/'),
('Developers.IO 2019 in TOKYO で「イマドキ！ユースケース別に見るAWS IoTへの接続パターン」を発表しました #cmdevio', '', 1, 'https://dev.classmethod.jp/articles/developers-io-2019-in-tokyo-how-to-connect-aws-iot/'),
('Step FunctionでAWS Glue のジョブやクローラーを呼び出すワークフローをつくってみた！', '', 1, 'https://dev.classmethod.jp/articles/step-function_workflow_for_glue_job/'),
('AWS Glue のジョブ同時実行数制限には気をつけた方がいいという話', '', 1, 'https://dev.classmethod.jp/articles/aws-glue-job-concurrency/'),
('[レポート] SORACOM のパートナー向けイベントに参加してきた！', '', 1, 'https://dev.classmethod.jp/articles/sps_technical_deep_dive_special/'),
('Auth0 + API Gateway で M2M 認証・認可をやってみた', '', 1, 'https://dev.classmethod.jp/articles/auth0-m2m-to-apigw-lambda-auth/'),
('[小ネタ] CloudWatch メトリクスのグラフをローカルに保存しちゃうぞ！', '', 1, 'https://dev.classmethod.jp/articles/clw_metrics_graph_export/'),
('[レポート] AWSで実現するマルチリージョン IoT 〜Analog Devicesの事例を添えて〜', '', 1, 'https://dev.classmethod.jp/articles/multi-region-iot/'),
('DynamoDBのLastEvaluatedKeyが示すレコードを削除した時の挙動について調べてみた', '', 1, 'https://dev.classmethod.jp/articles/ddb-lastevaluatedkey/'),
('AWS SAM (Serverless Application Model) で実現するカナリアリリース！', '', 1, 'https://dev.classmethod.jp/articles/aws-sam-aws-serverless-canary/'),
('[検証] Serverless Application Repository を使って、AWS SAMで品質の高いテンプレートを管理する！ #reinvent', '', 1, 'https://dev.classmethod.jp/articles/sam-app-repo/'),
('[レポート] IOT366: AWS IoT Things Graph の紹介 #reinvent', '', 1, 'https://dev.classmethod.jp/articles/report-iot366-aws-iot-things-reinvent/'),
('[速報] Lambda開発向けの VS Code 拡張機能が公式提供されました! #reinvent', '', 1, 'https://dev.classmethod.jp/articles/lambda-vscode-extension/'),
('[レポート] DAT201: Amazon DynamoDB の最新情報について！ #reinvent', '', 1, 'https://dev.classmethod.jp/articles/dat201-amazon-dynamodb-reinvent/'),
('Amazon DynamoDB On-Demandをためしてみた！ #reinvent', '', 1, 'https://dev.classmethod.jp/articles/amazon-dynamodb-on-demand-reinvent/'),
('[レポート] Amazon FreeRTOS の最新情報！ #reinvent #IOT208', '', 1, 'https://dev.classmethod.jp/articles/report-amazon-freertos-iot-operating-system-for-microcontrollers-reinvent/'),
('[レポート] APIで実現するデジタルトランスフォーメーション #reinvent #SRV323', '', 1, 'https://dev.classmethod.jp/articles/report-api-digital-transformation/'),
('[速報] 産業用機器からのデータ収集＆分析が手軽にできるマネージドサービス、AWS IoT SiteWise が発表されました #reinvent', '', 1, 'https://dev.classmethod.jp/articles/site-wise/'),
('[レポート] サーバーレスアーキテクチャのデザインパターンとベストプラクティス！ #reinvent #ARC305', '', 1, 'https://dev.classmethod.jp/articles/serverless-architectural-patterns-and-best-practices-reinvent-arc305/'),
('[速報] Amazon FreeRTOSでBLE(Bluetooth Low Energy)がサポートされました！ #reinvent', '', 1, 'https://dev.classmethod.jp/articles/amazon-freertos-ble-support-reinvent/'),
('AsyncAPIでつくるMQTTインターフェイス仕様書！', '', 1, 'https://dev.classmethod.jp/articles/asyncapi_mqtt_if/'),
('DynamoDBのオートスケーリング機能を有効にすると勝手に作成されるアラームについて調べてみた', '', 1, 'https://dev.classmethod.jp/articles/dynamo-db-auto-scaling/'),
('AWS IoT Device Simulatorを使ってみたら感動した！', '', 1, 'https://dev.classmethod.jp/articles/aws-iot-device-simulator/'),
('Lambdaが異常終了した際にアラート通知させる仕組みをAWS SAMのテンプレートで一括デプロイ', '', 1, 'https://dev.classmethod.jp/articles/sam-alert/'),
('AWS SAMでAPI Gatewayのリソースポリシーを設定してみた', '', 1, 'https://dev.classmethod.jp/articles/sam_apig_resource_policy/'),
('Cognitoから払い出された IdToken を API Gateway カスタムオーソライザーのLambdaで検証する方法', '', 1, 'https://dev.classmethod.jp/articles/verify_cognit_idtoken_by_apig_custom_auth/'),
('DynamoDBでElasticsearch Service/CloudSearch/SDK Scan に頼らず検索機能を実現する方法', '', 1, 'https://dev.classmethod.jp/articles/dynamodb-inverted-index/'),
('クラスメソッドのサーバーレス開発部にジョインしました新井です', '', 1, 'https://dev.classmethod.jp/articles/araiseiichi-join/');
 